language: php
sudo: false
php:
    - 8.0
cache:
    directories:
        - $HOME/.composer/cache
addons:
    sonarcloud:
        organization: "quillstack"
        token:
            secure: "gWZEyhJgsnDZlZ1V2D6j0rGofFSTf0UAo0YVR0/0VCGLZ8zXDQCf0bk4D8DqThPNfz4AAq+HWFMv3B2VjUNVZTbj+Kz8cqrChFtRhFStdD0i8bdLcz5xlyq6gwWrxWpYPIpx/OMNrPy1JPuvVBjoXfDC3Ny1rvEzmk+gtCJPf9+Ohkth7QMMmmh+JSHB8VORSTTr/NQr9B9gTG43dleVBOW/FXYgSFhIKCbsAGG21fyVkzct784FyqVlnNBcZJBzxBWsM5u3PyLPWS9IUiNXkvUeHjVX8faa1sKoSChLnOT4wttRpYVbi7N7ZUe7L4lmDZ7p9wMNdexHAj1XL+CAycTeWxA51jLu1lRDIgsrsRamFafsMXCqrztYlpQwvIDc6rONRKU4IIFAftvStipkiQ+4w4ujGerGXMMcFI8u0XOJT4o/7JNFwNe8oPudO24RuyqFaqM/dk2q7jY64W5nuzTMYjUJmEoOjxk9+xpCiVrN+DhpoK3UiZr1z2Tn7nu1JUjqklc+E22NJYfeHvki/btVf3QIT9E3eUPBgz6sjVss5l8l0EQ+90ze2ixsZb9rxw2vM3tT7iKe/UCN2ilczoMuV37TIwHccWMyPoqSQVLzRHUW45Ci8kZjXzkmpiNbu+b9d41woGsumyhqagIkzSr9n6pxguuVgbqj32HgGfE="
git:
    depth: false
install: composer update --no-interaction --no-suggest --no-progress
script:
    - phpdbg -qrr vendor/bin/phpunit  --coverage-clover phpunit.coverage.xml --log-junit phpunit.report.xml
    - sonar-scanner
