language: php
sudo: false
php:
    - 8.0
cache:
    directories:
        - $HOME/.composer/cache
addons:
    sonarcloud:
        organization: "quillstack"
        token:
            secure: "NVoE5TCaMgAyW31v4JeDt3VEQHzE+XlkZnMOrDYtCbL2CLqdAw7HzukJ9MmSMjg6us2zfzDZjPUlnGwOjm8CyYCA0ZeMidHVQokVajOQ5Xju79MpWt6xJ2SKY9fVzUUjjpAvxZRlyAyVrPp1aFZXNlM4OVUR0pL9AfZV/nLj+hc82EoPVYEZO71ZAD/YAxOFkTildHQFVbhgEdTrPgnU8tDYmIw8GHVIkJZd3u1n01/l+EdI+bj8mQzCgqPf7pBlXi8D7ZOXDiwRLJqsWADeqwa7kmjLpL6Gv4wKo8iw1fGBKx2qXMBpKgflhQnzOiG2G9vSeuk/7MbVbCIJWc36zVHYpLmeQchRlpSZsVtBpP/f2px6WyCMq65SFZxMSjv0YpdbS3dBjlHp2LZrFyqpzSltJBZMJOpTSRXss2ulpJBD92La8lHIu3RXVOvTORrK82Vz0W4f0Pc/tXiwKgWIBuOswgm7qfUXCPXyfW9e/cJlM7G4In7SxUfIESeNVcxPy9GAyZOUHkYrFBnkv9rCq96MDmg84WRorkXtpNo2aDfgW1Mw/OzMd+rbP5239gCADF8sI3VbcGd2mL+K6nHKtwGcP0P3+LXouanTbqpQIJ8wAwXJWnY2vMwmCPD5pWiV62Bw001bhFGMMe0q8qcJdkufQDob7ifDXBxWf1eYP9w="
git:
    depth: false
install: composer update --no-interaction --no-suggest --no-progress
script:
    - phpdbg -qrr vendor/bin/phpunit  --coverage-clover phpunit.coverage.xml --log-junit phpunit.report.xml
    - sonar-scanner
