language: php
sudo: false
php:
    - 8.0
cache:
    directories:
        - $HOME/.composer/cache
addons:
    sonarcloud:
        organization: "quillstack"
        token:
            secure: "av7EotTZC1+NFM3yIXjt86lzMAN1aawvZQimHFE+oUjIrJE2Gc6edW3vxAoF8r7L8KXHteevnzDnI+tPbvtcUMNfvSKFmpXO11wOig8vXN5nopL3Gjogmv/B1KfDfeQ9zB38VsVOyhDuBy+uhl/5mCqa7zLpby6nR5uhn/DxJCZsLy0aqMZy9X8rr5RL6rm1nD4f28r3gO6CGfHyGuNaZVG+vK8GVqeC11L1/J3AgDHw/JGj04rzSRkev95lQPktynNfVLS+9erdzZMV2vdBhWOAB2ci3up2UUW6oyr+DHJCbSwwtuUiBWW3FD3WEuy7vp7XmsX4mIA5R5lzAvfmGr+KyMt5AYod2uN36I22leNMrwvpPlzIy9i7zEafvbUq/kKIKkn4MB9d3KTrJJrA3cFdtJTY7lHcUT37yUqu5atAsivbf1CMyquZwcBtL7qL0RK0z0AbgZWeJyn2Fe1qQoXpsnNZ49NNzYuQO3zWspQ/h/0eyCdvIuUglzGXwK6DTz9xbYHdEz2dz945UAiuBhcFYVTC4qjabdEiVmbZayhXjh071rTK06L+WCgSU+q2cpRUjYHsFAZi7n3iHnfYlLYzdj7/Jz9OwZ1/ifmRGEsrBbRfjWWYONC0nudaqmNyCQEvbnrCXVXLzDb5IYFupDyy0nIM445atR9foUSiyvg="
git:
    depth: false
install: composer update --no-interaction --no-suggest --no-progress
script:
    - phpdbg -qrr vendor/bin/phpunit  --coverage-clover phpunit.coverage.xml --log-junit phpunit.report.xml
    - sonar-scanner
